# Figure 3 plotting.
# Purpose: render the retained manuscript panels as PNG only. Inputs are the
# stable tables generated by 01_build_figure3_data.R and
# 02_build_figure3_tables.R.
source(file.path("scripts", "00_setup", "helpers.R"))
suppressPackageStartupMessages({
  library(ggplot2)
  library(ggrepel)
  library(patchwork)
  library(scales)
  library(ComplexHeatmap)
  library(circlize)
  library(grid)
})

figure_dir <- file.path(project_root, "figures", "figure-3")
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

pool_cols <- c(Pool_1 = "#95A08E", Pool_2 = "#D4A280", Pool_3 = "#BB8086", Pool_4 = "#8087A2")
state_cols <- c(Crude = "#A0A5B7", Fractionated = "#9A4049")
direction_cols <- c("Higher in Pool_1" = "#404B74", "Higher in Pool_4" = "#9A4049", "Not significant" = "#C8C8C8")
figure1_pie_cols <- c(
  "#404B74", "#9A4049", "#406D80", "#965A78", "#BE7440",
  "#8087A2", "#BB8086", "#809DAA", "#B991A5", "#D4A280"
)
blend_hex <- function(hex, target, amount) {
  rgb1 <- grDevices::col2rgb(hex) / 255
  rgb2 <- grDevices::col2rgb(target) / 255
  rgb <- rgb1 * (1 - amount) + rgb2 * amount
  grDevices::rgb(rgb[1], rgb[2], rgb[3])
}
pool_prevalence_cols <- unlist(lapply(names(pool_cols), function(pool) {
  # Figure 3f uses hue for pool identity and shade for prevalence category:
  # dark = common, medium = shared, light = pool-unique.
  cols <- c(
    "Pool-unique" = blend_hex(pool_cols[[pool]], "white", 0.55),
    Shared = pool_cols[[pool]],
    Common = blend_hex(pool_cols[[pool]], "black", 0.28)
  )
  setNames(cols, paste(pool, names(cols), sep = "::"))
}))
pool_prevalence_levels <- as.vector(vapply(
  names(pool_cols),
  function(pool) paste(pool, c("Common", "Shared", "Pool-unique"), sep = "::"),
  character(3)
))
class_cols <- setNames(uom_discrete[c(2, 6, 10, 14, 18, 34, 38, 42, 46, 50, 27)], c(
  "Small peptides", "Fatty Acids and Conjugates", "Steroids", "Terpenoids",
  "Flavonoids", "Alkaloids", "Carbohydrates", "Aromatic compounds",
  "Polyketides", "Amino acids and Peptides", "Other"
))

theme_figure3 <- function(base_size = 20) {
  theme_classic(base_size = base_size, base_family = "Arial") +
    theme(
      axis.line = element_line(linewidth = 0.35),
      axis.ticks = element_line(linewidth = 0.35),
      plot.title = element_text(size = base_size + 0.5, face = "bold"),
      strip.text = element_text(face = "bold"),
      legend.title = element_text(size = base_size - 0.2),
      legend.text = element_text(size = base_size - 0.5),
      plot.margin = margin(7, 7, 7, 7)
    )
}
theme_set(theme_figure3())
fmt_int <- function(x) scales::number(x, accuracy = 1, big.mark = "")

pca <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-pca-scores.csv"), show_col_types = FALSE)
pooled_crude_pca <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-pooled-crude-pca-scores.csv"), show_col_types = FALSE)
individual_crude_pca <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-individual-crude-pca-scores.csv"), show_col_types = FALSE)
pooled_fraction_pca <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-pooled-fraction-pca-scores.csv"), show_col_types = FALSE)
cluster_order <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-crude-cluster-order.csv"), show_col_types = FALSE)
dist_long <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-crude-distance-matrix-long.csv"), show_col_types = FALSE)
volcano <- bind_rows(
  readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-volcano-crude.csv"), show_col_types = FALSE),
  readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-volcano-fractionated.csv"), show_col_types = FALSE)
)
prevalence <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-common-shared-pool-unique.csv"), show_col_types = FALSE)
class_breakdown <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-common-unique-class-breakdown.csv"), show_col_types = FALSE)
combined_prevalence <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-combined-pool-prevalence-by-confidence.csv"), show_col_types = FALSE)
combined_common_classes <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-combined-common-class-breakdown.csv"), show_col_types = FALSE)
permanova <- readr::read_csv(file.path(project_root, "outputs", "tables", "figure3-permanova.csv"), show_col_types = FALSE)

dist_matrix <- dist_long %>%
  select(profile_1, profile_2, distance) %>%
  pivot_wider(names_from = profile_2, values_from = distance) %>%
  tibble::column_to_rownames("profile_1") %>%
  as.matrix()
dist_matrix <- dist_matrix[rownames(dist_matrix), rownames(dist_matrix), drop = FALSE]
dist_hc <- hclust(as.dist(dist_matrix), method = "ward.D2")
pool_map <- setNames(cluster_order$combined_pool_id, cluster_order$profile_id)
pool_annotation <- factor(pool_map[colnames(dist_matrix)], levels = names(pool_cols))

human_meta <- read_hgm_sheet("H - Human Samples") %>%
  mutate(across(everything(), clean_text)) %>%
  filter(HGMH.ID %in% colnames(dist_matrix)) %>%
  distinct(HGMH.ID, .keep_all = TRUE)
meta_value <- function(column, fallback = "Unknown") {
  value <- human_meta[[column]][match(colnames(dist_matrix), human_meta$HGMH.ID)]
  factor(if_else(is.na(value) | value == "", fallback, value))
}
diet_annotation <- meta_value("Diet")
gender_annotation <- meta_value("Gender")
ethnicity_annotation <- meta_value("Ethnicity")
meta_palette <- function(x, colours) {
  setNames(rep(colours, length.out = nlevels(x)), levels(x))
}
metadata_annotation <- data.frame(
  Pool = pool_annotation,
  Diet = diet_annotation,
  Gender = gender_annotation,
  Ethnicity = ethnicity_annotation,
  row.names = colnames(dist_matrix),
  check.names = FALSE
)
top_ha <- HeatmapAnnotation(
  df = metadata_annotation,
  col = list(
    Pool = pool_cols,
    Diet = meta_palette(diet_annotation, c("#E5A000", "#56ADD9", "#A7A7A7")),
    Gender = meta_palette(gender_annotation, c("#4F7CAC", "#F28E2B", "#A7A7A7")),
    Ethnicity = meta_palette(ethnicity_annotation, c("#E5A000", "#56ADD9", "#009B77", "#F4DF42", "#A7A7A7"))
  ),
  show_legend = TRUE,
  simple_anno_size = unit(4.2, "mm"),
  gap = unit(0.8, "mm"),
  annotation_name_side = "left",
  annotation_name_rot = 0,
  annotation_name_gp = gpar(fontfamily = "Arial", fontsize = 14, fontface = "bold"),
  annotation_legend_param = list(
    Pool = list(
      title_gp = gpar(fontfamily = "Arial", fontsize = 14, fontface = "bold"),
      labels_gp = gpar(fontfamily = "Arial", fontsize = 12)
    ),
    Diet = list(title_gp = gpar(fontfamily = "Arial", fontsize = 14, fontface = "bold"), labels_gp = gpar(fontfamily = "Arial", fontsize = 12)),
    Gender = list(title_gp = gpar(fontfamily = "Arial", fontsize = 14, fontface = "bold"), labels_gp = gpar(fontfamily = "Arial", fontsize = 12)),
    Ethnicity = list(title_gp = gpar(fontfamily = "Arial", fontsize = 14, fontface = "bold"), labels_gp = gpar(fontfamily = "Arial", fontsize = 12))
  )
)
cluster_ht <- Heatmap(
  dist_matrix,
  name = "Distance",
  col = circlize::colorRamp2(
    c(min(dist_matrix[dist_matrix > 0]), median(dist_matrix[dist_matrix > 0]), max(dist_matrix)),
    c("#F4F5F8", "#A0A5B7", "#404B74")
  ),
  cluster_rows = dist_hc,
  cluster_columns = dist_hc,
  top_annotation = top_ha,
  show_row_dend = TRUE,
  show_column_dend = TRUE,
  row_names_side = "right",
  row_names_gp = gpar(fontfamily = "Arial", fontsize = 12),
  row_names_max_width = unit(38, "mm"),
  column_names_gp = gpar(fontfamily = "Arial", fontsize = 11),
  column_names_rot = 45,
  heatmap_legend_param = list(
    title_gp = gpar(fontfamily = "Arial", fontsize = 18, fontface = "bold"),
    labels_gp = gpar(fontfamily = "Arial", fontsize = 16)
  )
)
cluster_grob <- grid::grid.grabExpr(
  ComplexHeatmap::draw(
    cluster_ht,
    heatmap_legend_side = "right",
    annotation_legend_side = "right",
    merge_legends = TRUE,
    legend_gap = unit(8, "mm"),
    padding = unit(c(4, 48, 10, 4), "mm")
  ),
  width = 15,
  height = 10
)
p_cluster <- patchwork::wrap_elements(full = cluster_grob)

make_pca <- function(state_name, title) {
  d <- pca %>%
    filter(state == state_name) %>%
    mutate(ellipse_group = interaction(combined_pool_id, processing_level, drop = TRUE))
  ellipse_groups <- d %>% count(ellipse_group) %>% filter(n >= 4) %>% pull(ellipse_group)
  ellipse_data <- d %>% filter(ellipse_group %in% ellipse_groups)
  stat <- permanova %>% filter(state == state_name, term != "Residual", term != "Total") %>% slice_head(n = 1)
  p <- ggplot(d, aes(PC1, PC2, colour = combined_pool_id)) +
    geom_point(aes(shape = if (state_name == "Fractionated") processing_level else NULL), size = 1.7, alpha = 0.8)
  if (state_name == "Fractionated") {
    p <- p +
      stat_ellipse(
        data = ellipse_data,
        aes(group = ellipse_group),
        type = "norm", level = 0.8, linewidth = 0.5, show.legend = FALSE
      )
  }
  p +
    scale_colour_manual(values = pool_cols, name = "Pool") +
    labs(
      title = title,
      x = paste0("PC1 (", percent(d$pc1_variance[[1]], accuracy = 0.1), ")"),
      y = paste0("PC2 (", percent(d$pc2_variance[[1]], accuracy = 0.1), ")"),
      shape = "Fraction type"
    )
}
p_pca_crude <- make_pca("Crude", "Crude profiles retain individual variability")
p_pca_fraction <- make_pca("Fractionated", "Fraction-resolved profiles amplify pool differences")
p_pca_fraction <- p_pca_fraction +
  guides(
    shape = guide_legend(order = 1, nrow = 1),
    colour = guide_legend(order = 2, nrow = 1)
  ) +
  theme(
    legend.position = "bottom",
    legend.box = "vertical",
    legend.box.just = "left",
    legend.margin = margin(t = 2),
    legend.spacing.y = unit(0.08, "cm"),
    legend.key.width = unit(0.42, "cm"),
    legend.key.height = unit(0.35, "cm"),
    legend.title = element_text(size = 12.5, face = "bold"),
    legend.text = element_text(size = 11.5),
    plot.margin = margin(7, 7, 7, 7)
  )

pooled_stat <- permanova %>%
  filter(state == "Pooled crude", term == "combined_pool_id") %>%
  slice_head(n = 1)
p_pca_crude <- ggplot(
  pooled_crude_pca,
  aes(PC1, PC2, colour = combined_pool_id, shape = processing_level)
) +
  geom_point(size = 4.2, alpha = 0.92) +
  scale_colour_manual(values = pool_cols, name = "Pool") +
  labs(
    title = "Pool-aggregated crude profiles",
    x = paste0("PC1 (", percent(pooled_crude_pca$pc1_variance[[1]], accuracy = 0.1), ")"),
    y = paste0("PC2 (", percent(pooled_crude_pca$pc2_variance[[1]], accuracy = 0.1), ")"),
    shape = "Crude type"
  ) +
  guides(
    shape = guide_legend(order = 1, nrow = 1),
    colour = guide_legend(order = 2, nrow = 1)
  ) +
  theme(
    legend.position = "bottom",
    legend.box = "vertical",
    legend.box.just = "left",
    legend.margin = margin(t = 2),
    legend.spacing.y = unit(0.08, "cm"),
    legend.key.width = unit(0.42, "cm"),
    legend.key.height = unit(0.35, "cm"),
    legend.title = element_text(size = 12.5, face = "bold"),
    legend.text = element_text(size = 11.5),
    plot.margin = margin(7, 7, 7, 7)
  )

p_candidate_individual_crude <- ggplot(
  individual_crude_pca,
  aes(PC1, PC2, colour = combined_pool_id)
) +
  geom_point(size = 3.4, alpha = 0.9) +
  ggrepel::geom_text_repel(
    aes(label = profile_id),
    size = 3.6,
    max.overlaps = Inf,
    box.padding = 0.35,
    show.legend = FALSE
  ) +
  scale_colour_manual(values = pool_cols, name = "Pool") +
  labs(
    title = "Individual-level crude PCA",
    x = paste0("PC1 (", percent(individual_crude_pca$pc1_variance[[1]], accuracy = 0.1), ")"),
    y = paste0("PC2 (", percent(individual_crude_pca$pc2_variance[[1]], accuracy = 0.1), ")")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 13, face = "bold"),
    legend.text = element_text(size = 12),
    plot.margin = margin(9, 9, 9, 9)
  )

p_candidate_pooled_fraction <- ggplot(
  pooled_fraction_pca,
  aes(PC1, PC2, colour = combined_pool_id)
) +
  geom_point(size = 4.8, alpha = 0.92) +
  ggrepel::geom_text_repel(
    aes(label = str_replace(combined_pool_id, "_", " ")),
    size = 4.2,
    fontface = "bold",
    max.overlaps = Inf,
    box.padding = 0.45,
    show.legend = FALSE
  ) +
  scale_colour_manual(values = pool_cols, name = "Pool") +
  labs(
    title = "Pool-level fraction PCA",
    x = paste0("PC1 (", percent(pooled_fraction_pca$pc1_variance[[1]], accuracy = 0.1), ")"),
    y = paste0("PC2 (", percent(pooled_fraction_pca$pc2_variance[[1]], accuracy = 0.1), ")")
  ) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 13, face = "bold"),
    legend.text = element_text(size = 12),
    plot.margin = margin(9, 9, 9, 9)
  )

volcano <- volcano %>%
  mutate(plot_p = -log10(pmax(fdr, 1e-300)), short_label = if_else(fdr < 0.01 & abs(effect) >= 1, coalesce(compound.name, annotation_id), NA_character_))
make_volcano <- function(state_name) {
  d <- volcano %>% filter(state == state_name)
  ggplot(d, aes(effect, plot_p, colour = direction)) +
    geom_point(size = 0.7, alpha = 0.55) +
    geom_vline(xintercept = c(-1, 1), linetype = 2, linewidth = 0.3) +
    geom_hline(yintercept = -log10(0.05), linetype = 2, linewidth = 0.3) +
    ggrepel::geom_text_repel(
      data = d %>% filter(!is.na(short_label)),
      aes(label = short_label), max.overlaps = 8, size = 3.75, box.padding = 0.3, show.legend = FALSE
    ) +
    scale_colour_manual(
      values = direction_cols,
      breaks = c("Higher in Pool_1", "Higher in Pool_4", "Not significant"),
      labels = c("Higher in Pool 1", "Higher in Pool 4", "Not significant")
    ) +
    labs(title = paste(state_name, "differential features"), x = "log2 fold change\n(Pool 4 / Pool 1)", y = "-log10(BH-adjusted FDR)", colour = "Direction") +
    theme(
      legend.position = "inside",
      legend.position.inside = c(0.56, 0.96),
      legend.direction = "horizontal",
      legend.title = element_blank(),
      legend.text = element_text(size = 9.5),
      legend.background = element_rect(fill = alpha("white", 0.85), colour = NA)
    )
}
top_changes <- readr::read_csv(
  file.path(project_root, "outputs", "tables", "figure3-top-changing-metabolites.csv"),
  show_col_types = FALSE
)
make_top_change <- function(state_name) {
  top_changes %>%
    filter(state == state_name) %>%
    slice_head(n = 10) %>%
    mutate(
      significance = -log10(pmax(fdr, 1e-300)),
      fdr_label = if_else(fdr < 0.001, format(fdr, scientific = TRUE, digits = 2), format(round(fdr, 3), nsmall = 3)),
      label_short = paste0(str_trunc(label, 26), "\nFDR = ", fdr_label),
      label_short = factor(label_short, levels = rev(label_short))
    ) %>%
    ggplot(aes(effect, label_short, size = significance, colour = direction)) +
    geom_point(alpha = 0.82) +
    geom_vline(xintercept = 0, linewidth = 0.3) +
    scale_colour_manual(values = direction_cols, guide = "none") +
    scale_size_continuous(
      name = expression(-log[10]("BH-adjusted FDR")),
      range = c(3.5, 11),
      breaks = scales::breaks_pretty(n = 3)
    ) +
    labs(title = "Top 10 changed features", x = "log2 fold change", y = NULL) +
    theme_figure3(14.5) +
    theme(
      axis.text.y = element_text(size = 9.6, lineheight = 0.9),
      plot.title = element_text(size = 15),
      legend.position = "bottom",
      legend.title = element_text(size = 10.5),
      legend.text = element_text(size = 9.5),
      legend.key.width = unit(0.7, "cm")
    )
}
p_volcano_crude <- wrap_elements(full = wrap_plots(
  list(make_volcano("Crude"), make_top_change("Crude")),
  ncol = 2, widths = c(1, 1)
))
p_volcano_fraction <- wrap_elements(full = wrap_plots(
  list(make_volcano("Fractionated"), make_top_change("Fractionated")),
  ncol = 2, widths = c(1, 1)
))

prevalence_plot_data <- combined_prevalence %>%
  mutate(
    confidence.level = factor(paste0("Level ", confidence.level), levels = paste0("Level ", 1:3)),
    category = factor(category, levels = c("Common", "Shared", "Pool-unique")),
    pool_category = factor(paste(combined_pool_id, category, sep = "::"), levels = pool_prevalence_levels),
    label_colour = if_else(category == "Common", "white", "black")
  ) %>%
  arrange(confidence.level, combined_pool_id, category) %>%
  group_by(confidence.level, combined_pool_id) %>%
  mutate(
    label_ymin = lag(cumsum(annotations), default = 0),
    label_ymax = cumsum(annotations),
    label_y = if_else(annotations < 40, label_ymax + 20, (label_ymin + label_ymax) / 2)
  ) %>%
  ungroup()
p_prevalence <- prevalence_plot_data %>%
  ggplot(aes(combined_pool_id, annotations, fill = pool_category)) +
  # Keep the visual order fixed: common at the baseline, shared in the middle,
  # pool-unique at the top. Label y-positions are precomputed above so colour
  # aesthetics cannot accidentally alter the text stack order.
  geom_col(position = position_stack(reverse = TRUE)) +
  geom_text(
    aes(y = label_y, label = fmt_int(annotations), colour = label_colour),
    size = 4.2,
    family = "Arial",
    fontface = "bold",
    show.legend = FALSE
  ) +
  facet_wrap(~confidence.level, nrow = 1) +
  scale_fill_manual(
    values = pool_prevalence_cols,
    breaks = paste("Pool_1", c("Common", "Shared", "Pool-unique"), sep = "::"),
    labels = c("Common", "Shared", "Pool-unique"),
    name = "Prevalence",
    guide = guide_legend(nrow = 1, override.aes = list(linewidth = 0))
  ) +
  scale_colour_identity() +
  scale_y_continuous(expand = expansion(mult = c(0.02, 0.08))) +
  labs(
    title = "Combined crude and fraction annotations across pools",
    x = NULL,
    y = "Non-repeating annotations"
  ) +
  theme(axis.text.x = element_text(angle = 35, hjust = 1), legend.position = "top")

p_class_data <- combined_common_classes %>%
  filter(superclass != "Unclassified") %>%
  arrange(desc(annotations)) %>%
  slice_head(n = 10) %>%
  mutate(
    superclass_plot = superclass,
    superclass_plot = factor(superclass_plot, levels = rev(unique(superclass_plot[order(annotations)])))
  ) %>%
  group_by(superclass_plot) %>%
  summarise(annotations = sum(annotations), .groups = "drop") %>%
  mutate(
    fraction = annotations / sum(annotations),
    label = if_else(fraction >= 0.05, paste0(fmt_int(annotations), "\n", superclass_plot), "")
  )
class_levels <- levels(p_class_data$superclass_plot)
class_cols <- setNames(
  vapply(rep(figure1_pie_cols, length.out = length(class_levels)), blend_hex, character(1), target = "white", amount = 0.32),
  class_levels
)
p_class <- p_class_data %>%
  ggplot(aes(x = 1, y = annotations, fill = superclass_plot)) +
  geom_col(width = 1, colour = "white", linewidth = 0.35) +
  coord_polar(theta = "y") +
  geom_text(
    aes(label = label),
    position = position_stack(vjust = 0.5),
    size = 4.2,
    family = "Arial",
    lineheight = 0.9
  ) +
  scale_fill_manual(values = class_cols, name = "NPClassifier superclass", guide = guide_legend(ncol = 1)) +
  labs(
    title = "Chemical-class composition of common metabolites",
    x = NULL,
    y = NULL
  ) +
  theme_void(base_size = 16, base_family = "Arial") +
  theme(
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA),
    plot.title = element_text(size = 17, face = "bold", hjust = 0),
    legend.position = "right",
    legend.title = element_text(size = 13, face = "bold"),
    legend.text = element_text(size = 12),
    plot.margin = margin(7, 7, 7, 7)
  )

top_row <- (p_cluster | p_pca_crude | p_pca_fraction) +
  plot_layout(widths = c(2, 1, 1))
middle_row <- (p_volcano_crude | p_volcano_fraction) +
  plot_layout(widths = c(1, 1))
bottom_row <- (p_prevalence | p_class) +
  plot_layout(widths = c(2, 1))

figure3 <- top_row / middle_row / bottom_row +
  plot_layout(heights = c(3, 3, 2), guides = "keep") +
  plot_annotation(
    tag_levels = "a",
    theme = theme(
      plot.tag = element_text(size = 36, face = "bold", family = "Arial"),
      plot.margin = margin(8, 8, 8, 8)
    )
  )

base <- file.path(figure_dir, "figure3-assembled")
ggsave(paste0(base, ".png"), figure3, width = 34, height = 24, dpi = 300)

# Export each retained manuscript panel independently for downstream assembly.
individual_panels <- list(
  "figure3a-crude-clustering.png" = list(plot = p_cluster, width = 17, height = 12),
  "figure3b-pooled-crude-pca.png" = list(plot = p_pca_crude, width = 14, height = 11),
  "figure3c-fraction-resolved-pca.png" = list(plot = p_pca_fraction, width = 14, height = 11),
  "figure3d-crude-volcano.png" = list(plot = p_volcano_crude, width = 15, height = 8),
  "figure3e-fractionated-volcano.png" = list(plot = p_volcano_fraction, width = 15, height = 8),
  "figure3f-prevalence.png" = list(plot = p_prevalence, width = 11, height = 8),
  "figure3g-common-class-pie.png" = list(plot = p_class, width = 11, height = 8),
  "figure3-candidate-individual-crude-pca.png" = list(plot = p_candidate_individual_crude, width = 12, height = 9),
  "figure3-candidate-pooled-fraction-pca.png" = list(plot = p_candidate_pooled_fraction, width = 12, height = 9)
)
purrr::iwalk(individual_panels, function(spec, filename) {
  ggsave(
    file.path(figure_dir, filename),
    spec$plot,
    width = spec$width,
    height = spec$height,
    dpi = 300
  )
})
