source(file.path("scripts", "00_setup", "helpers.R"))
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(readr)
  library(scales)
  library(stringr)
  library(tidyr)
})

# Figure 5 follow-up analysis.
# Purpose:
# 1. Test which NPClassifier superclasses are enriched among atlas-only
#    identities compared with atlas identities that overlap HMDB and/or MiMeDB.
# 2. Audit steroid/bile-acid-like annotations by evidence source, so this class
#    is not interpreted as inflated by a single in silico source.
#
# Inputs are generated by scripts/08_figure5/01_build_figure5.R and the
# classified atlas total list. Re-run 01_build_figure5.R first if HMDB/MiMeDB
# identity matching has changed.

audit_path <- file.path(project_root, "outputs", "qc", "figure5-identity-and-lipid-audit.csv")
atlas_path <- file.path(project_root, "data", "processed", "paper2_total_list_classified.csv")
table_dir <- file.path(project_root, "outputs", "tables")
figure_dir <- file.path(project_root, "figures", "figure-4")

for (p in c(audit_path, atlas_path)) {
  if (!file.exists(p)) stop("Missing input: ", p)
}

theme_followup <- function(base_size = 16) {
  theme_classic(base_size = base_size, base_family = "Arial") +
    theme(
      axis.line = element_line(linewidth = 0.35, colour = "#2B2B2B"),
      axis.ticks = element_line(linewidth = 0.35, colour = "#2B2B2B"),
      axis.text = element_text(colour = "#2B2B2B"),
      axis.title = element_text(colour = "#2B2B2B"),
      legend.title = element_text(face = "bold"),
      plot.title = element_text(face = "bold", size = base_size + 2),
      panel.grid = element_blank()
    )
}

norm_text <- function(x) clean_text(x)

membership <- readr::read_csv(audit_path, show_col_types = FALSE, progress = FALSE) %>%
  mutate(
    collection = norm_text(collection),
    identity_key = norm_text(identity_key),
    npc_superclass = norm_text(npc_superclass)
  ) %>%
  filter(identity_key != "")

atlas_classified <- readr::read_csv(atlas_path, show_col_types = FALSE, progress = FALSE) %>%
  mutate(
    annotation_id = norm_text(annotation_id),
    compound.name = norm_text(compound.name),
    annotation.type = norm_text(annotation.type),
    npc_superclass = norm_text(npc_superclass),
    npc_class = norm_text(npc_class),
    canopus.NPC.superclass = norm_text(canopus.NPC.superclass),
    canopus.classyfire.superclass = norm_text(canopus.classyfire.superclass),
    gnps.library.usi = norm_text(gnps.library.usi),
    gnps.in.silico.bile.acid.info = norm_text(gnps.in.silico.bile.acid.info)
  )

identity_membership <- membership %>%
  distinct(identity_key, collection) %>%
  mutate(present = TRUE) %>%
  pivot_wider(names_from = collection, values_from = present, values_fill = FALSE)

for (nm in c("Human faecal atlas", "Healthy HMDB", "MiMeDB")) {
  if (!nm %in% names(identity_membership)) identity_membership[[nm]] <- FALSE
}

atlas_identity_status <- identity_membership %>%
  filter(.data[["Human faecal atlas"]]) %>%
  transmute(
    identity_key,
    atlas_reference_status = if_else(
      .data[["Healthy HMDB"]] | .data[["MiMeDB"]],
      "Overlapping HMDB/MiMeDB",
      "Atlas-only"
    )
  )

atlas_identity_classes <- membership %>%
  filter(collection == "Human faecal atlas") %>%
  distinct(identity_key, source_id, npc_superclass) %>%
  left_join(atlas_identity_status, by = "identity_key") %>%
  filter(
    atlas_reference_status %in% c("Atlas-only", "Overlapping HMDB/MiMeDB"),
    npc_superclass != "",
    npc_superclass != "Unclassified"
  )

class_universe <- atlas_identity_classes %>%
  distinct(identity_key, atlas_reference_status, npc_superclass)

status_totals <- class_universe %>%
  distinct(identity_key, atlas_reference_status) %>%
  count(atlas_reference_status, name = "identity_total")

enrichment <- class_universe %>%
  distinct(identity_key, atlas_reference_status, npc_superclass) %>%
  group_by(npc_superclass) %>%
  summarise(
    atlas_only_with_class = n_distinct(identity_key[atlas_reference_status == "Atlas-only"]),
    overlap_with_class = n_distinct(identity_key[atlas_reference_status == "Overlapping HMDB/MiMeDB"]),
    .groups = "drop"
  ) %>%
  mutate(
    atlas_only_total = status_totals$identity_total[match("Atlas-only", status_totals$atlas_reference_status)],
    overlap_total = status_totals$identity_total[match("Overlapping HMDB/MiMeDB", status_totals$atlas_reference_status)],
    atlas_only_without_class = atlas_only_total - atlas_only_with_class,
    overlap_without_class = overlap_total - overlap_with_class
  ) %>%
  rowwise() %>%
  mutate(
    fisher_p = fisher.test(matrix(
      c(atlas_only_with_class, atlas_only_without_class, overlap_with_class, overlap_without_class),
      nrow = 2,
      byrow = TRUE
    ))$p.value,
    odds_ratio = as.numeric(fisher.test(matrix(
      c(atlas_only_with_class, atlas_only_without_class, overlap_with_class, overlap_without_class),
      nrow = 2,
      byrow = TRUE
    ))$estimate)
  ) %>%
  ungroup() %>%
  mutate(
    fdr = p.adjust(fisher_p, method = "BH"),
    atlas_only_fraction = atlas_only_with_class / atlas_only_total,
    overlap_fraction = overlap_with_class / overlap_total,
    enrichment_direction = case_when(
      atlas_only_fraction > overlap_fraction ~ "Enriched in atlas-only",
      atlas_only_fraction < overlap_fraction ~ "Enriched in overlap",
      TRUE ~ "No direction"
    )
  ) %>%
  arrange(fdr, desc(odds_ratio), desc(atlas_only_with_class))

evidence_rank <- c(
  "In silico bile-acid-library supported" = 1L,
  "Authentic-standard/library-supported" = 2L,
  "Direct spectral-library match" = 3L,
  "Spectral-neighbour/analogue annotation" = 4L,
  "In silico structure/class prediction" = 5L,
  "Other or unresolved evidence" = 6L
)

atlas_evidence <- atlas_classified %>%
  mutate(
    evidence_category = case_when(
      gnps.in.silico.bile.acid.info != "" ~ "In silico bile-acid-library supported",
      annotation.type == "authentic standard" | confidence.level == 1 ~ "Authentic-standard/library-supported",
      annotation.type %in% c("gnps", "mzmine") | gnps.library.usi != "" ~ "Direct spectral-library match",
      annotation.type == "ms2query" ~ "Spectral-neighbour/analogue annotation",
      annotation.type == "CSI:FingerID" ~ "In silico structure/class prediction",
      TRUE ~ "Other or unresolved evidence"
    ),
    evidence_rank = evidence_rank[evidence_category]
  ) %>%
  group_by(annotation_id) %>%
  arrange(evidence_rank, desc(confidence.score), .by_group = TRUE) %>%
  slice_head(n = 1) %>%
  ungroup()

atlas_identity_evidence <- atlas_identity_classes %>%
  left_join(atlas_evidence, by = c("source_id" = "annotation_id"), suffix = c("", ".atlas"))

atlas_identity_all <- membership %>%
  filter(collection == "Human faecal atlas") %>%
  distinct(identity_key, source_id) %>%
  left_join(atlas_identity_status, by = "identity_key") %>%
  left_join(atlas_evidence, by = c("source_id" = "annotation_id"))

enriched_top <- enrichment %>%
  filter(enrichment_direction == "Enriched in atlas-only", atlas_only_with_class >= 10) %>%
  arrange(fdr, desc(odds_ratio)) %>%
  slice_head(n = 15) %>%
  mutate(npc_superclass = reorder(npc_superclass, odds_ratio))

p_enrichment <- ggplot(enriched_top, aes(odds_ratio, npc_superclass)) +
  geom_vline(xintercept = 1, colour = "#C8C8C8", linewidth = 0.35) +
  geom_point(aes(size = atlas_only_with_class, colour = -log10(fdr)), alpha = 0.92) +
  scale_x_log10(labels = label_number(accuracy = 0.1)) +
  scale_size_continuous(name = "Atlas-only\nidentities", range = c(3.8, 9.5)) +
  scale_colour_gradient(low = "#C9D8D4", high = "#617156", name = expression(-log[10]("FDR"))) +
  labs(
    title = "Atlas-only class enrichment",
    x = "Odds ratio for atlas-only enrichment",
    y = NULL
  ) +
  theme_followup(16) +
  theme(legend.position = "right")

top_class_evidence <- atlas_identity_evidence %>%
  semi_join(enriched_top %>% select(npc_superclass), by = "npc_superclass") %>%
  distinct(identity_key, npc_superclass, evidence_category) %>%
  count(npc_superclass, evidence_category, name = "identity_count") %>%
  group_by(npc_superclass) %>%
  mutate(class_total = sum(identity_count)) %>%
  ungroup()

steroid_regex <- regex(
  paste(
    c(
      "steroid", "sterol", "bile", "cholic", "cholanic", "cholenoic",
      "BA core",
      "deoxycholic", "chenodeoxycholic", "ursodeoxycholic", "lithocholic",
      "hydroxystear", "pregnen", "androsten", "estr", "cortico"
    ),
    collapse = "|"
  ),
  ignore_case = TRUE
)

steroid_audit <- atlas_identity_all %>%
  mutate(
    steroid_bile_flag = str_detect(coalesce(npc_superclass, ""), steroid_regex) |
      str_detect(coalesce(npc_class, ""), steroid_regex) |
      str_detect(coalesce(canopus.NPC.superclass, ""), steroid_regex) |
      str_detect(coalesce(canopus.classyfire.superclass, ""), steroid_regex) |
      str_detect(coalesce(compound.name, ""), steroid_regex),
    steroid_evidence_group = case_when(
      gnps.in.silico.bile.acid.info != "" ~ "In silico bile-acid-library supported",
      annotation.type == "authentic standard" | confidence.level == 1 ~ "Authentic-standard/library-supported",
      annotation.type %in% c("gnps", "mzmine") | gnps.library.usi != "" ~ "Spectral-library match",
      TRUE ~ "Class-level/computational only"
    )
  ) %>%
  filter(steroid_bile_flag) %>%
  group_by(identity_key) %>%
  arrange(match(steroid_evidence_group, c(
    "In silico bile-acid-library supported",
    "Authentic-standard/library-supported",
    "Spectral-library match",
    "Class-level/computational only"
  )), desc(confidence.score), .by_group = TRUE) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  transmute(
    identity_key,
    annotation_id = source_id,
    compound_name = compound.name,
    atlas_reference_status,
    steroid_evidence_group,
    annotation_type = annotation.type,
    confidence_level = confidence.level,
    confidence_score = confidence.score,
    npc_superclass = coalesce(npc_superclass, ""),
    npc_class = coalesce(npc_class, ""),
    canopus_npc_superclass = coalesce(canopus.NPC.superclass, ""),
    gnps_library_usi = coalesce(gnps.library.usi, ""),
    in_silico_bile_acid_info = coalesce(gnps.in.silico.bile.acid.info, ""),
    dataset_ids = coalesce(source_dataset_ids, ""),
    source_dataset_count = source_dataset_count,
    source_feature_count = source_feature_count
  )

steroid_summary <- steroid_audit %>%
  count(atlas_reference_status, steroid_evidence_group, name = "identity_count") %>%
  group_by(atlas_reference_status) %>%
  mutate(status_total = sum(identity_count), fraction = identity_count / status_total) %>%
  ungroup()

steroid_order <- c(
  "Class-level/computational only",
  "Spectral-library match",
  "Authentic-standard/library-supported",
  "In silico bile-acid-library supported"
)

steroid_cols <- c(
  "Authentic-standard/library-supported" = "#617156",
  "Spectral-library match" = "#9FB39A",
  "In silico bile-acid-library supported" = "#BE7440",
  "Class-level/computational only" = "#D6D6D6"
)

p_steroid <- steroid_summary %>%
  mutate(
    atlas_reference_status = factor(atlas_reference_status, levels = c("Overlapping HMDB/MiMeDB", "Atlas-only")),
    steroid_evidence_group = factor(steroid_evidence_group, levels = steroid_order)
  ) %>%
  ggplot(aes(atlas_reference_status, identity_count, fill = steroid_evidence_group)) +
  geom_col(width = 0.64, colour = "#333333", linewidth = 0.25) +
  geom_text(
    aes(label = identity_count),
    position = position_stack(vjust = 0.5),
    family = "Arial",
    size = 4.4,
    colour = "#222222"
  ) +
  scale_fill_manual(values = steroid_cols, name = "Evidence tier", drop = FALSE) +
  labs(
    title = "Steroid and bile-acid-like audit",
    x = NULL,
    y = "Non-repeating identities"
  ) +
  theme_followup(16) +
  theme(
    legend.position = "right",
    axis.text.x = element_text(face = "bold")
  )

write_csv_stable(enrichment, file.path(table_dir, "figure5-atlas-only-class-enrichment.csv"))
write_csv_stable(top_class_evidence, file.path(table_dir, "figure5-atlas-only-enriched-class-evidence.csv"))
write_csv_stable(steroid_audit, file.path(table_dir, "figure5-steroid-bile-acid-audit.csv"))
write_csv_stable(steroid_summary, file.path(table_dir, "figure5-steroid-bile-acid-evidence-summary.csv"))

ggsave(file.path(figure_dir, "figure5e-atlas-only-class-enrichment.png"), p_enrichment, width = 10.32, height = 7.68, dpi = 300, bg = "white")
ggsave(file.path(figure_dir, "figure5f-steroid-bile-acid-audit.png"), p_steroid, width = 4.92, height = 3.12, dpi = 300, bg = "white")

message("Figure 5 follow-up enrichment and steroid/bile-acid audit complete.")
message("Atlas-only identities in enrichment universe: ", status_totals$identity_total[match("Atlas-only", status_totals$atlas_reference_status)])
message("Overlapping atlas identities in enrichment universe: ", status_totals$identity_total[match("Overlapping HMDB/MiMeDB", status_totals$atlas_reference_status)])
message("Steroid/bile-acid-like identities audited: ", nrow(steroid_audit))
